// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// imr2638_rx //
// ---------- //

#define imr2638_rx_wrap_target 0
#define imr2638_rx_wrap 17
#define imr2638_rx_pio_version 0

static const uint16_t imr2638_rx_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0xe020, //  1: set    x, 0
    0xa029, //  2: mov    x, ~x
    0x00c5, //  3: jmp    pin, 5
    0x0043, //  4: jmp    x--, 3
    0xa0c9, //  5: mov    isr, ~x
    0xe041, //  6: set    y, 1
    0x4041, //  7: in     y, 1
    0x8000, //  8: push   noblock
    0xe020, //  9: set    x, 0
    0xa029, // 10: mov    x, ~x
    0x00cd, // 11: jmp    pin, 13
    0x000e, // 12: jmp    14
    0x004b, // 13: jmp    x--, 11
    0xa0c9, // 14: mov    isr, ~x
    0xe040, // 15: set    y, 0
    0x4041, // 16: in     y, 1
    0x8000, // 17: push   noblock
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program imr2638_rx_program = {
    .instructions = imr2638_rx_program_instructions,
    .length = 18,
    .origin = -1,
    .pio_version = imr2638_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config imr2638_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + imr2638_rx_wrap_target, offset + imr2638_rx_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void imr2638_rx_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = imr2638_rx_program_get_default_config(offset);
    // Set input pin and jump pin
    sm_config_set_in_pins(&c, pin);
    sm_config_set_jmp_pin(&c, pin);
    // Configure GPIO as PIO input with pull-up
    pio_gpio_init(pio, pin);
    gpio_set_pulls(pin, true, false);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);
    // Shift left, no autopush, 32 bits
    sm_config_set_in_shift(&c, false, false, 32);
    // Set clock divider: 2 cycles per count iteration -> 2.0 MHz
    float div = (float)clock_get_hz(clk_sys) / 2000000.0f;
    sm_config_set_clkdiv(&c, div);
    // Load config and initialize state machine
    pio_sm_init(pio, sm, offset, &c);
}

#endif

