// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// ir_tx //
// ----- //

#define ir_tx_wrap_target 0
#define ir_tx_wrap 9
#define ir_tx_pio_version 0

static const uint16_t ir_tx_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x603f, //  1: out    x, 31
    0x6041, //  2: out    y, 1
    0x0068, //  3: jmp    !y, 8
    0xe001, //  4: set    pins, 1
    0xe000, //  5: set    pins, 0
    0x0044, //  6: jmp    x--, 4
    0x0000, //  7: jmp    0
    0xe100, //  8: set    pins, 0                [1]
    0x0048, //  9: jmp    x--, 8
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ir_tx_program = {
    .instructions = ir_tx_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = ir_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ir_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ir_tx_wrap_target, offset + ir_tx_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void ir_tx_program_init(PIO pio, uint sm, uint offset, uint pin, uint32_t freq_hz) {
    pio_sm_config c = ir_tx_program_get_default_config(offset);
    // Set pin as SET pin
    sm_config_set_set_pins(&c, pin, 1);
    // Initialize GPIO for PIO
    pio_gpio_init(pio, pin);
    gpio_set_dir(pin, GPIO_OUT);
    gpio_put(pin, false);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // Shift left, no autopush/autopull, 32 bits
    sm_config_set_out_shift(&c, false, false, 32);
    // Set clock divider: 3 PIO cycles per carrier period
    if (freq_hz == 0) {
        freq_hz = 38000;
    }
    float pio_clock = (float)(freq_hz * 3);
    float div = (float)clock_get_hz(clk_sys) / pio_clock;
    sm_config_set_clkdiv(&c, div);
    // Load config and initialize state machine
    pio_sm_init(pio, sm, offset, &c);
}
static inline void ir_tx_set_freq(PIO pio, uint sm, uint32_t freq_hz) {
    if (freq_hz == 0) {
        freq_hz = 38000;
    }
    float pio_clock = (float)(freq_hz * 3);
    float div = (float)clock_get_hz(clk_sys) / pio_clock;
    pio_sm_set_clkdiv(pio, sm, div);
}

#endif

